### ISSUE TITLE
Files inspected, no offenses detected for data_magic gem

### ISSUE THREAD

**Issue by ivodimitrov** [koic/rubocop-faker#4]
I'm using in Gemfile:
```gem 'bundler'
gem 'data_magic'
gem 'page-object'
gem 'rubocop-faker'
gem 'rspec'
gem 'rspec-expectations'
```

Code in default.yml is:
```
forgot_password_page: email_address: ~email_address
```

and in forgot_password_page.rb is:
```class ForgotPasswordPage 
  include PageObject
  include DataMagic

  def submit_forgot_password(data = {})
    populate_page_with data_for(:forgot_password_page, data)
  end
end
```

After I ran the test the following error is displayed:

> gems/data_magic-1.2/lib/data_magic/standard_translation.rb:187: Passing `name` with the 1st argument of `email` is deprecated. Use keyword argument like `email(name: ...)` instead.

After I ran:
`rubocop \
  --require rubocop-faker \
  --only Faker/DeprecatedArguments \
  --auto-correct`

the output is: 

> 44 files inspected, no offenses detected

**Comment by koic** [comment]
This is a data_magic gem's warning. Can you open a PR or issue to data_magic repository?
https://github.com/cheezy/data_magic

Thank you.

**Comment by ivodimitrov** [comment]
Thank you for your informative reply! I will open issue to data_magic. 
Unfortunately support and contributing there is very slow.
I guess we can close the issue here.
Sorry for interrupting you with bugs not related to rubocop-faker!
