### ISSUE TITLE
New Release Requested to avoid Deprecation Warning

### ISSUE THREAD

**Issue by rmm5t** [koic/rubocop-faker#7]
@koic Could we please get a new release of rubocop-faker?

The current version (1.1.0) gives this deprecation warning with rubocop 1.67, but it appears this deprecation warning was already resolved in `master`.

```
.../gems/rubocop-faker-1.1.0/lib/rubocop/cop/faker/deprecated_arguments.rb:17: warning: Inheriting from `RuboCop::Cop::Cop` is deprecated. Use `RuboCop::Cop::Base` instead.
For more information, see https://docs.rubocop.org/rubocop/v1_upgrade_notes.html.
```

**Comment by koic** [comment]
RuboCop Faker 1.12.0 has been released. Thank you for your feedback!
https://github.com/koic/rubocop-faker/releases/tag/v1.2.0
